# Generated by Django 6.0.3 on 2026-05-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_utilisateur_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='otp_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
