services:
  - type: web
    name: nexora-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --workers 1 --threads 1 --timeout 120"
    envVars:
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_FROM_EMAIL
        sync: false
      - key: SENDGRID_FROM_NAME
        value: "Nexora"
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: EMAIL_USE_TLS
        sync: false
      - key: EMAIL_USE_SSL
        sync: false
      - key: SMTP_FROM_EMAIL
        sync: false
      - key: DEMO_OTP_MODE
        value: "False"
      - key: NOVA_OCR_BASE_URL
        value: "http://51.20.136.48:8000"
      - key: NOVA_OCR_API_KEY
        sync: false
      - key: NOVA_OCR_TIMEOUT
        value: "45"
      - key: NOVA_BIOMETRIC_BASE_URL
        value: "http://51.20.136.48:8000"
      - key: NOVA_BIOMETRIC_API_KEY
        sync: false
      - key: NOVA_BIOMETRIC_TIMEOUT
        value: "45"
      - key: RSS_SOC_APP_NAME
        value: "nexora-api"
      - key: RSS_SOC_URL
        value: "http://198.199.70.48:3100"
      - key: RSS_SOC_TOKEN
        value: "rssbank-token-2024"
      - key: RSS_SOC_ENV
        value: "production"
      - key: RSS_SOC_LOCAL_LOGS
        value: "/app/logs"
      - key: RSS_SOC_BLOCK_ATTACKS
        value: "true"
      - key: RSS_SOC_BAN_DURATION
        value: "3600"
      - key: RSS_SOC_EMAIL_ALERTS
        value: "false"
