# Generated by Django 6.0.3 on 2026-05-10 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('SUCCESS', 'Succès'), ('FAILED', 'Échec'), ('PENDING', 'En attente')], max_length=20)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_transactions', to='users.utilisateur')),
            ],
        ),
    ]
