from django.urls import path

from .views import (
    activate_user,
    ban_user,
    change_role,
    check_admin_exists,
    create_user,
    delete_user,
    detect_anomalies,
    detect_suspicious_behavior,
    forgot_password,
    get_activity_timeline,
    get_audit,
    get_logs,
    get_my_alerts,
    get_my_logs,
    get_my_profile,
    get_my_stats,
    get_security_status,
    get_user,
    get_users,
    register_client,
    reset_password,
    suspend_user,
    track_login,
    update_my_profile,
    update_user,
)


urlpatterns = [
    path("", get_users),
    path("create/", create_user),
    path("<int:id>/", get_user),
    path("update/<int:id>/", update_user),
    path("delete/<int:id>/", delete_user),
    path("suspend/<int:id>/", suspend_user),
    path("activate/<int:id>/", activate_user),
    path("ban/<int:id>/", ban_user),
    path("change-role/<int:id>/", change_role),
    path("reset-password/<int:id>/", reset_password),
    path("profile/", get_my_profile),
    path("profile/update/", update_my_profile),
    path("me/", get_my_profile),
    path("my-logs/", get_my_logs),
    path("me/alerts/", get_my_alerts),
    path("stats/", get_my_stats),
    path("logs/", get_logs),
    path("audit/", get_audit),
    path("timeline/", get_activity_timeline),
    path("security-status/", get_security_status),
    path("detect-anomalies/", detect_anomalies),
    path("detect-behavior/", detect_suspicious_behavior),
    path("track-login/", track_login),
    path("check-admin/", check_admin_exists),
    path("forgot-password/", forgot_password, name="forgot_password"),
    path("register/", register_client),
]
