# Generated by Django 6.0.3 on 2026-05-10 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('CREATE_USER', 'Créer utilisateur'), ('UPDATE_USER', 'Modifier utilisateur'), ('DELETE_USER', 'Supprimer utilisateur'), ('GENERATE_REPORT', 'Générer rapport')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.utilisateur')),
            ],
        ),
    ]
