# Generated by Django 6.0.3 on 2026-05-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
    ]
