# Generated by Codex on 2026-06-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0002_log_is_suspicious"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="entity_id",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="log",
            name="entity_type",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="log",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="log",
            name="severity",
            field=models.CharField(
                choices=[
                    ("INFO", "Info"),
                    ("WARNING", "Warning"),
                    ("CRITICAL", "Critical"),
                ],
                default="INFO",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="log",
            name="target_repr",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="log",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Connexion"),
                    ("LOGOUT", "Déconnexion"),
                    ("CREATE_USER", "Créer utilisateur"),
                    ("UPDATE_USER", "Modifier utilisateur"),
                    ("DELETE_USER", "Supprimer utilisateur"),
                    ("SUSPEND_USER", "Suspendre utilisateur"),
                    ("ACTIVATE_USER", "Réactiver utilisateur"),
                    ("BAN_USER", "Bannir utilisateur"),
                    ("CHANGE_ROLE", "Changer rôle"),
                    ("RESET_PASSWORD", "Réinitialiser mot de passe"),
                    ("UPDATE_PROFILE", "Mettre à jour profil"),
                    ("SUBMIT_KYC", "Soumettre KYC"),
                    ("APPROVE_KYC", "Approuver KYC"),
                    ("REJECT_KYC", "Rejeter KYC"),
                    ("CREATE_TRANSACTION", "Créer transaction"),
                    ("APPROVE_TRANSACTION", "Approuver transaction"),
                    ("REJECT_TRANSACTION", "Rejeter transaction"),
                    ("GENERATE_REPORT", "Générer rapport"),
                ],
                max_length=50,
            ),
        ),
    ]

