# Generated by Django 6.0.3 on 2026-05-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycrequest',
            name='date_naissance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kycrequest',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kycrequest',
            name='nni',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kycrequest',
            name='nom_famille',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kycrequest',
            name='ocr_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycrequest',
            name='prenom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kycrequest',
            name='prenom_pere',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kycrequest',
            name='sexe',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
